### ISSUE TITLE
Can't import vocab; ImportError: No module named vocab

### ISSUE THREAD

**Issue by Adnandev123** [vzhong/vocab#1]
Hi,

I'm trying to install and import vocab. It successfully installed but shows an error when I try to import.

>>> from vocab import Vocab, UnkVocab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users0/ahmadan/.local/lib/python2.7/site-packages/vocab/__iniy", line 1, in <module>
    from vocab.vocab import Vocab, OutOfVocabularyException
ImportError: No module named vocab

**Comment by vzhong** [comment]
can you tell me how you installed this? I can't seem to reproduce this problem.

```
pip install vocab
python -c 'import vocab'
```

**Comment by vzhong** [comment]
Closing due to lack of activity.

**Comment by sunhf** [comment]
I also have this problem. I solved it by changing the code in "__init__.py" to "from vocab import Vocab, OutOfVocabularyException"

**Comment by vzhong** [comment]
ahhh I think I see the problem now. Should be fixed by 84c05c9f69533d61e6a883398262ea9019717ab8. Thanks guys!

**Comment by vzhong** [comment]
You can also get this fix by `pip install vocab --upgrade`. I just upped the version number as well.
